### ISSUE TITLE
Client and server crash if you call rm on a directory

### ISSUE THREAD

**Issue by LangTowl** [LangTowl/cloud-server-project#22]

**Comment by LangTowl** [comment]
<img width="568" alt="image" src="https://github.com/user-attachments/assets/6210e493-4743-4ca7-9d78-1e1189831eed">

**Comment by Lukas-k03** [comment]
Added if statement to check if the file has an extension, if not reject the rm command
![image](https://github.com/user-attachments/assets/66a85a84-2953-467f-b96f-9919fc98e35d)
