### ISSUE TITLE
Client crash if you run cd without passing in a directory name

### ISSUE THREAD

**Issue by LangTowl** [LangTowl/cloud-server-project#33]
<img width="782" alt="image" src="https://github.com/user-attachments/assets/8ff76e09-dc3f-4f21-bb81-5b23d2dfcfa5">

**Comment by Lukas-k03** [comment]
This happens with any command that has two parts
added a check for if I needs the second part of the message if its not there it will prompt the user of there fault
![image](https://github.com/user-attachments/assets/24ae6003-9398-4ee6-b0a0-c5d676274a80)
